[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tdkit"
version = "0.0.1"
description = "A toolkit for time domain astronomy"
authors = [{name = "Luis Salazar Manzano", email = "lesamz@umich.edu"}]
dependencies = ["numpy", "pandas"]